### ISSUE TITLE
How do i receive the money

### ISSUE THREAD

**Issue by Kolhax** [Nohet/linkvertise.py#1]
i see no places where do i can link it to my linvertise account, so idk how do i should receive money?

**Comment by Nohet** [comment]
publisher.linkvertise.com -> log in -> Full Script API -> there is your account id
![obraz](https://user-images.githubusercontent.com/70505658/147848236-160a638b-b905-4154-aa28-2a438eb902b6.png)

Now when you have your id, paste it into code:
`<client>.linkvertise(account_id, url)`
